// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Wageworks.Feature.Navigation.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {AF39EA75-D5F8-4290-A1F4-0A55D3CF258E} in Sitecore.
	/// Path: /sitecore/templates/Feature/Navigation/_LinkDescription
	/// </summary>
	[SitecoreType(TemplateId = "{AF39EA75-D5F8-4290-A1F4-0A55D3CF258E}")]
	public partial interface ILinkDescription
	{
		#region Navigation

		/// <summary>
		/// Description - Shown in extended link components
		/// </summary>
	    [SitecoreField(FieldId = "{448F2DB8-C477-4D21-835E-CE7583491B24}")]
		string Description { get; set; }

		#endregion

	}
}
