// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Wageworks.Feature.Navigation.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {A1CBA309-D22B-46D5-80F8-2972C185363F} in Sitecore.
	/// Path: /sitecore/templates/Feature/Navigation/_Navigable
	/// </summary>
	[SitecoreType(TemplateId = "{A1CBA309-D22B-46D5-80F8-2972C185363F}")]
	public partial interface INavigable
	{
		#region Navigation

		/// <summary>
		/// Short title - Title shown in menus and areas where space is limited
		/// </summary>
	    [SitecoreField(FieldId = "{1B483E91-D8C4-4D19-BA03-462074B55936}")]
		string NavigationTitle { get; set; }

		/// <summary>
		/// Show Children in Menus
		/// </summary>
	    [SitecoreField(FieldId = "{68016087-AA00-45D6-922A-678475C50D4A}")]
		bool ShowChildren { get; set; }

		/// <summary>
		/// Show in navigation menus
		/// </summary>
	    [SitecoreField(FieldId = "{5585A30D-B115-4753-93CE-422C3455DEB2}")]
		bool ShowInNavigation { get; set; }

		#endregion

	}
}
