// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Wageworks.Feature.Navigation.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {F9F4FC05-98D0-4C62-860F-F08AE7F0EE25} in Sitecore.
	/// Path: /sitecore/templates/Feature/Navigation/_NavigationRoot
	/// </summary>
	[SitecoreType(TemplateId = "{F9F4FC05-98D0-4C62-860F-F08AE7F0EE25}")]
	public partial interface INavigationRoot
	{
	}
}
